version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html/api
        ports:
            - "80:80"
        links:
            - php-fpm
        networks:
            - backend

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin
        environment:
             - PGADMIN_DEFAULT_EMAIL=user@domain.com
             - PGADMIN_DEFAULT_PASSWORD=SuperSecret
             - PGADMIN_LISTEN_PORT=5050
        ports:
            - "5050:5050"
        networks:
            - backend


    php-fpm:
        container_name: php-fpm
        restart: always
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - .:/var/www/html/api
        networks:
            - backend

    postgres:
        container_name: postgresql
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: dev
        networks:
            - backend

networks:
    backend:
        driver: bridge
